/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_system.ADMIN;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import library_system.dbConnection;

/**
 *
 * @author Mi HI Ri
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
      Connection conn=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    public IssueBook() {
        initComponents();
        conn=dbConnection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userSearch = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bookN = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel51 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        auth = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pyear = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pric = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Descrip = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        updt = new javax.swing.JLabel();
        bookIdSearch = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        getdate = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel56 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 13, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Issuebook100 (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issue Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon close.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchbook.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter User ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 90, 20));

        userSearch.setBackground(new java.awt.Color(16, 13, 29));
        userSearch.setForeground(new java.awt.Color(255, 255, 255));
        userSearch.setBorder(null);
        userSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchActionPerformed(evt);
            }
        });
        jPanel1.add(userSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 190, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 190, 10));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookName.png"))); // NOI18N
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Enter Book ID");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        bookN.setBackground(new java.awt.Color(16, 13, 29));
        bookN.setForeground(new java.awt.Color(255, 255, 255));
        bookN.setBorder(null);
        bookN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNActionPerformed(evt);
            }
        });
        jPanel1.add(bookN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, 20));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, 10));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-male-user-24.png"))); // NOI18N
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Author");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        auth.setBackground(new java.awt.Color(16, 13, 29));
        auth.setForeground(new java.awt.Color(255, 255, 255));
        auth.setBorder(null);
        auth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authActionPerformed(evt);
            }
        });
        jPanel1.add(auth, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 190, 20));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 190, 10));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/year.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Published Year");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        pyear.setBackground(new java.awt.Color(16, 13, 29));
        pyear.setForeground(new java.awt.Color(255, 255, 255));
        pyear.setBorder(null);
        pyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyearActionPerformed(evt);
            }
        });
        jPanel1.add(pyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 190, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 190, 10));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/price.png"))); // NOI18N
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        Pric.setBackground(new java.awt.Color(16, 13, 29));
        Pric.setForeground(new java.awt.Color(255, 255, 255));
        Pric.setBorder(null);
        Pric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PricActionPerformed(evt);
            }
        });
        jPanel1.add(Pric, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 190, 20));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, 10));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 20));

        Descrip.setBackground(new java.awt.Color(16, 13, 29));
        Descrip.setForeground(new java.awt.Color(255, 255, 255));
        Descrip.setBorder(null);
        Descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripActionPerformed(evt);
            }
        });
        jPanel1.add(Descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 190, 40));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 190, 10));

        updt.setBackground(new java.awt.Color(0, 153, 153));
        updt.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        updt.setForeground(new java.awt.Color(255, 255, 255));
        updt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        updt.setText("Issue");
        updt.setOpaque(true);
        updt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updtMouseClicked(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 90, 30));

        bookIdSearch.setBackground(new java.awt.Color(16, 13, 29));
        bookIdSearch.setForeground(new java.awt.Color(255, 255, 255));
        bookIdSearch.setBorder(null);
        bookIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdSearchActionPerformed(evt);
            }
        });
        bookIdSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookIdSearchKeyPressed(evt);
            }
        });
        jPanel1.add(bookIdSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 190, 20));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Book Name");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage book.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("User Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        username.setBackground(new java.awt.Color(16, 13, 29));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 190, 20));
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 190, 10));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Get Date");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/getdate24.png"))); // NOI18N
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        getdate.setBackground(new java.awt.Color(16, 13, 29));
        getdate.setForeground(new java.awt.Color(255, 255, 255));
        getdate.setBorder(null);
        getdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdateActionPerformed(evt);
            }
        });
        jPanel1.add(getdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 190, 20));
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 190, 10));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duedate24.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Due Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        duedate.setBackground(new java.awt.Color(16, 13, 29));
        duedate.setForeground(new java.awt.Color(255, 255, 255));
        duedate.setBorder(null);
        duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateActionPerformed(evt);
            }
        });
        jPanel1.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 190, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 190, 10));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-male-user-24.png"))); // NOI18N
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("State");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sugees24.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        State.setBackground(new java.awt.Color(16, 13, 29));
        State.setForeground(new java.awt.Color(255, 255, 255));
        State.setBorder(null);
        State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateActionPerformed(evt);
            }
        });
        jPanel1.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 190, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 190, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        MenuAdmin obj=new MenuAdmin();
        obj.setVisible(true);
        obj.pack();
        obj.setLocationRelativeTo(null);
        obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        String query="select * from USER where userID=?";
        String search=userSearch.getText();

        try {
            pst=conn.prepareStatement(query);
            pst.setString(1, search);
            rs=pst.executeQuery();

            if(rs.next()){
                String userName=rs.getString("userName");
                username.setText(userName);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(manageBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    }//GEN-LAST:event_jLabel24MouseClicked

    private void userSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSearchActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void bookNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNActionPerformed

    private void authActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authActionPerformed

    private void pyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pyearActionPerformed

    private void PricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PricActionPerformed

    private void DescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripActionPerformed

    private void updtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updtMouseClicked
          
            // TODO add your handling code here:
             try {
            // TODO add your handling code here:
            String Bid= bookIdSearch.getText();
            String Uid=userSearch.getText();
            String Bname= bookN.getText(); 
            String author= auth.getText();
            String Pyear =pyear.getText();
            String price =Pric.getText();
            String description =Descrip.getText();
            String Uname=username.getText();
            String Gdate=getdate.getText();
            String Ddate=duedate.getText();
            
            
            String query="insert into ISSUEBOOK(bookID,userID,bookName,author,publishedYear,price,userName,getDate,dueDate,description)values(?,?,?,?,?,?,?,?,?,?)";
            pst =conn.prepareStatement (query);
            pst.setString(1, Bid);
            pst.setString(2, Uid);
            pst.setString(3, Bname);
            pst.setString(4, author);
            pst.setString(5, Pyear);
            pst.setString(6, price);
            pst.setString(7, Uname);
            pst.setString(8, Gdate);
            pst.setString(9, Ddate);
            pst.setString(10, description);
            if(pst.executeUpdate() !=0){
                JOptionPane.showMessageDialog(this,"Book issued Successfully");
                
            }
            else{
                JOptionPane.showMessageDialog(this,"Something wrong");
            }
        } catch (SQLException ex) {
            Logger.getLogger(addBook.class.getName()).log(Level.SEVERE, null, ex);
        }
             
           try {
            // TODO add your handling code here:
           Statement pst1=conn.createStatement();
           pst1.executeUpdate("UPDATE BOOK SET state='"+State.getText()
                   +"' where bookID='"+bookIdSearch.getText()+"'");
             JOptionPane.showMessageDialog(this, "Book State Update Successfully");
           
        } catch (SQLException ex) {
            Logger.getLogger(manageBook.class.getName()).log(Level.SEVERE, null, ex);
        }
     
            
    }//GEN-LAST:event_updtMouseClicked

    private void bookIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdSearchActionPerformed

    private void bookIdSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIdSearchKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_bookIdSearchKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        String query="select * from BOOK where bookID=?";
        String search=bookIdSearch.getText();

        try {
            pst=conn.prepareStatement(query);
            pst.setString(1, search);
            rs=pst.executeQuery();

            if(rs.next()){
                String bookName=rs.getString("bookName");
                bookN.setText(bookName);
                String author=rs.getString("author");
                auth.setText(author);
                String pubYear=rs.getString("publishedYear");
                pyear.setText(pubYear);
                String price=rs.getString("price");
                Pric.setText(price);
                String description=rs.getString("description");
                Descrip.setText(description);
                String state=rs.getString("state");
                State.setText(state);
            }
        } catch (SQLException ex) {
            Logger.getLogger(manageBook.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void getdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getdateActionPerformed

    private void duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateActionPerformed

    private void StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descrip;
    private javax.swing.JTextField Pric;
    private javax.swing.JTextField State;
    private javax.swing.JTextField auth;
    private javax.swing.JTextField bookIdSearch;
    private javax.swing.JTextField bookN;
    private javax.swing.JTextField duedate;
    private javax.swing.JTextField getdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField pyear;
    private javax.swing.JLabel updt;
    private javax.swing.JTextField userSearch;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
