/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_system.ADMIN;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library_system.dbConnection;

/**
 *
 * @author Mi HI Ri
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */ Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public ReturnBook() {
        initComponents();
          conn=dbConnection.ConnecrDb();
    showDate();
    }
    
    void showDate (){
    
    Date date=new Date();
    SimpleDateFormat dat= new SimpleDateFormat("yyyy-MM-dd");
    rDate.setDate(date);
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userSearch = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Calc = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lateDays = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fine = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        returntable = new javax.swing.JTable();
        updt1 = new javax.swing.JLabel();
        rDate = new com.toedter.calendar.JDateChooser();
        dueDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 13, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dateDetails100.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon close.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchbook.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter User ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, 20));

        userSearch.setBackground(new java.awt.Color(16, 13, 29));
        userSearch.setForeground(new java.awt.Color(255, 255, 255));
        userSearch.setBorder(null);
        userSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userSearchMouseClicked(evt);
            }
        });
        userSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchActionPerformed(evt);
            }
        });
        jPanel1.add(userSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 190, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 190, 10));

        Calc.setBackground(new java.awt.Color(0, 153, 153));
        Calc.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        Calc.setForeground(new java.awt.Color(255, 255, 255));
        Calc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duedate24.png"))); // NOI18N
        Calc.setText("Calculate");
        Calc.setOpaque(true);
        Calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcMouseClicked(evt);
            }
        });
        jPanel1.add(Calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 90, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/duedate24.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Due Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/returndate24.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Return Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/year.png"))); // NOI18N
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Number of Late Days ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        lateDays.setBackground(new java.awt.Color(16, 13, 29));
        lateDays.setForeground(new java.awt.Color(255, 255, 255));
        lateDays.setBorder(null);
        lateDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lateDaysActionPerformed(evt);
            }
        });
        jPanel1.add(lateDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 190, 20));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 190, 10));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/price.png"))); // NOI18N
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Fine");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        fine.setBackground(new java.awt.Color(16, 13, 29));
        fine.setForeground(new java.awt.Color(255, 255, 255));
        fine.setBorder(null);
        fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineActionPerformed(evt);
            }
        });
        jPanel1.add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 190, 20));
        jPanel1.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 190, 10));

        returntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookId", "Book Name", "Price", "Author", "Get Date", "Due Date"
            }
        ));
        jScrollPane1.setViewportView(returntable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 530, 270));

        updt1.setBackground(new java.awt.Color(0, 153, 153));
        updt1.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        updt1.setForeground(new java.awt.Color(255, 255, 255));
        updt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        updt1.setText("Finish");
        updt1.setOpaque(true);
        updt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updt1MouseClicked(evt);
            }
        });
        jPanel1.add(updt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 90, 30));
        jPanel1.add(rDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, -1));
        jPanel1.add(dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcMouseClicked
            try{ 
            SimpleDateFormat simpleDF=new SimpleDateFormat("MM/dd/yyyy",Locale.ENGLISH);
             Date firstDate =dueDate.getDate();
             Date secondDate=rDate.getDate();
             
             long diff=Math.abs(secondDate.getTime() - firstDate.getTime());
             long ndiff= TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
             
             lateDays.setText(String.valueOf(ndiff));
             
             if(ndiff>14){
              
               long total=ndiff*2;
               fine.setText(String.valueOf(total));
             
             }
             else{
               fine.setText("No fine");
             }
            }catch(Exception e){
            
                e.printStackTrace();
            
            }
            
    }//GEN-LAST:event_CalcMouseClicked

    private void userSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSearchActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here: String query="select * from BOOK";
         String query="select * from ISSUEBOOK where userID=?";
         String search=userSearch.getText();
        try  {
            
             pst =conn.prepareStatement(query);
             pst.setString(1, search);
             rs=pst.executeQuery();
            
            while(rs.next()){
            String Bid=rs.getString("bookID");
            String Bname=rs.getString("bookName");
            String author=rs.getString("author");
            String Price=String.valueOf(rs.getInt("price"));
            String Gdate=rs.getString("getDate");
            String Ddate=rs.getString("dueDate");
          
            
            String tbData[] ={Bid,Bname,author,Price,Gdate,Ddate};
            
            DefaultTableModel tblModel=(DefaultTableModel)returntable.getModel();
            
            tblModel.addRow(tbData);
            
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(manageBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
                
                

    
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        MenuAdmin obj=new MenuAdmin();
        obj.setVisible(true);
        obj.pack();
        obj.setLocationRelativeTo(null);
        obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void userSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userSearchMouseClicked

    private void lateDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lateDaysActionPerformed

    private void fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fineActionPerformed

    private void updt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updt1MouseClicked
        // TODO add your handling code here:
        int row =returntable.getSelectedRow();
        String Selection =returntable.getModel().getValueAt(row,0).toString();
        try {
              
            Statement pst=conn.createStatement();
            Statement pst1=conn.createStatement();

           
            
              pst.executeUpdate("DELETE FROM ISSUEBOOK WHERE userID='"+userSearch.getText()+"'");
              pst1.executeUpdate("UPDATE BOOK SET state='"+"Available"+"' where bookID='"+Selection+"'");
  

            
            // pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record Removed succsessfully");
          
          
          
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_updt1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calc;
    private com.toedter.calendar.JDateChooser dueDate;
    private javax.swing.JTextField fine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField lateDays;
    private com.toedter.calendar.JDateChooser rDate;
    private javax.swing.JTable returntable;
    private javax.swing.JLabel updt1;
    private javax.swing.JTextField userSearch;
    // End of variables declaration//GEN-END:variables
}
